### ISSUE TITLE
[Dev Console]: vscode code formating issue

### ISSUE THREAD

**Issue by eftehassanpp** [modular/mojo#1710]
### Issue description

when i write code and everytime i try to write a parameter or add a function call the indentation is auto removed and most of the case the line fall out of the function scope. then i need to manually add the indentation again

### Steps to reproduce

see the screenshot line 12 self.data.free when i add () after the code it automatically removes the indentation 
<img width="1440" alt="Screenshot 2024-01-31 at 15 14 01" src="https://github.com/modularml/mojo/assets/115105010/219acb53-98b3-4990-a5b4-2f74bb406577">
<img width="1440" alt="Screenshot 2024-01-31 at 15 13 28" src="https://github.com/modularml/mojo/assets/115105010/ae685959-87ec-4024-bcd5-d1928f96770a">

**Comment by eftehassanpp** [comment]
also in line 4 when i add the parameter [Int] after the Pointer it removes the indentation

**Comment by soraros** [comment]
@eftehassanpp Do you mind attach your code in text instead of just in screenshots?

**Comment by eftehassanpp** [comment]
from memory.unsafe import Pointer

struct HeapArray:
    var data:Pointer[Int]
    var size:Int
    fn __init__(inout self, size:Int,val:Int):
        self.size =size
        self.data=Pointer[Int].alloc(self.size)
        for i in range(self.size):
            self.data[i] =val
    fn __del__(owned self):
        self.data.free()
    fn dump(self):
        print_no_newline("[")
        for i in range(self.size):
            if i >0:
                print_no_newline(", ")
            print_no_newline(self.data.load(i))
        print("]")
    fn __copyinit__(inout self,existing:Self):
        self.size = existing.size
        self.data=Pointer[Int].alloc(self.size)
        for i in range(self.size):
            self.data[i] =existing.data[i]
fn main()->None:
    let x=HeapArray(3,1)
    let y=x
    x.dump()
    y.dump()

**Comment by eftehassanpp** [comment]
from memory.unsafe import Pointer

struct HeapArray:
    var data:Pointer[Int]
    var size:Int
    fn __init__(inout self, size:Int,val:Int):
        self.size =size
        self.data=Pointer[Int].alloc(self.size)
        for i in range(self.size):
            self.data[i] =val
    fn __del__(owned self):
        self.data.free()
    fn dump(self):
        print_no_newline("[")
        for i in range(self.size):
            if i >0:
                print_no_newline(", ")
            print_no_newline(self.data.load(i))
        print("]")
    fn __copyinit__(inout self,existing:Self):
        self.size = existing.size
        self.data=Pointer[Int].alloc(self.size)
        for i in range(self.size):
            self.data[i] =existing.data[i]
fn main()->None:
    let x=HeapArray(3,1)
    let y=x
    x.dump()
    y.dump()

**Comment by eftehassanpp** [comment]
from memory.unsafe import Pointer

struct HeapArray:
    var data:Pointer[Int]
    var size:Int
    fn __init__(inout self, size:Int,val:Int):
        self.size =size
        self.data=Pointer[Int].alloc(self.size)
        for i in range(self.size):
            self.data[i] =val
    fn __del__(owned self):
        self.data.free()
    fn dump(self):
        print_no_newline("[")
        for i in range(self.size):
            if i >0:
                print_no_newline(", ")
            print_no_newline(self.data.load(i))
        print("]")
    fn __copyinit__(inout self,existing:Self):
        self.size = existing.size
        `self.data=Pointer[Int].alloc(self.size)`
        for i in range(self.size):
            self.data[i] =existing.data[i]
fn main()->None:
    let x=HeapArray(3,1)
    let y=x
    x.dump()
    y.dump()

**Comment by eftehassanpp** [comment]
`from memory.unsafe import Pointer

struct HeapArray:
    var data:Pointer[Int]
    var size:Int
    fn __init__(inout self, size:Int,val:Int):
        self.size =size
        self.data=Pointer[Int].alloc(self.size)
        for i in range(self.size):
            self.data[i] =val
    fn __del__(owned self):
        self.data.free()
    fn dump(self):
        print_no_newline("[")
        for i in range(self.size):
            if i >0:
                print_no_newline(", ")
            print_no_newline(self.data.load(i))
        print("]")
    fn __copyinit__(inout self,existing:Self):
        self.size = existing.size
        self.data=Pointer[Int].alloc(self.size)
        for i in range(self.size):
            self.data[i] =existing.data[i]
fn main()->None:
    let x=HeapArray(3,1)
    let y=x
    x.dump()
    y.dump()
`

**Comment by soraros** [comment]
@eftehassanpp Could you wrap your code in triple back quote like the following?
````
```
Your code here
```
````

**Comment by mikowals** [comment]
From the screen shots I can see you are on MacOS.  I am on the same and don't see any of the behaviour you describe.  

If I had your issue, I would:

1. check that your Mojo version and Mojo VS extension version both match.  Probably easiest if they are both on the latest but I have been on several past versions of both and have not seen this issue.  So matching version numbers is probably sufficient.
2. Disable any other extensions that may be doing formatting.  I would probably just disable everything, then just enable the Mojo extension.   Hopefully that would fix the issue and then you can turn other extensions back on 1-by-1 to isolate the specific cause.   

But it definitely seems like something specific to your setup

**Comment by eftehassanpp** [comment]
the issue was happening for eslint .eslint not formatting correctly the mojo codes.
