### ISSUE TITLE
 [Docs] Explain what it is __getitem__ ,  __rsub__ , __rfloordiv__ , __iand__ , ....... etc

### ISSUE THREAD

**Issue by pharaoh0101** [modular/mojo#1992]
### Where is the problem?

There is no explanation for __getitem__  , __or__ etc ....

### What can we do better?

Add an explanation to it in the documents

### Anything else?

There are novice programmers who do not have a background in Python, and we want you to make the documents a scientific material rich in information.

**Comment by Brian-M-J** [comment]
The Modular team has written a [blog post](https://www.modular.com/blog/what-are-dunder-methods-a-guide-in-mojo) about dunder methods.
